from time import sleep
def start():
    name = "TSANIYA"
    print("\t\ti i i")
    sleep(1)
    print("\t\ti i i")
    sleep(1)
    print("\t:---------------------:")
    print("\t:    ++   HAPPY  ++   :")
    sleep(1)
    print("\t:    ++ MARRIAGE ++   :")
    sleep(1)
    print(f"\t:   ++  {name} ++    :")
    print("\t/_____________________\ ")
    sleep(.25)
    print("\t:-:-:-:-:-:-:-:-:-:-:-:")
    sleep(.25)
    print("\t:-:-:-:-:-:-:-:-:-:-:-:")
    sleep(.25)
    print("\t:-:-:-:-:-:-:-:-:-:-:-:")
    sleep(.25)
    print("\t/_____________________\ ")
    sleep(.25)
    print("\t||  ||  ||  ||  ||  ||  ")
    sleep(.25)
    print("\t||  ||  ||  ||  ||  ||  ")
    sleep(.25)
    print("\t||  ||  ||  ||  ||  ||  ")
    sleep(.25)
    print("\t||  ||  ||  ||  ||  ||  ")
    sleep(.25)
    print("\t||  ||  ||  ||  ||  ||  ")
    sleep(.5)
    print("Loading......")
    sleep(1)
    print("A message to you......")
    sleep(4)
    print("\t SELAMAT MENIKAH!!!, semoga menjadii keluarga sakinah mawaddah warrahmah :):):)")

a = input("1.TYPE 'xscore'\n2.PRESS 'ENTER'KEY\n(ELSE TYPE 'QUIT' TO QUIT\n\n:").lower()
if (a == "xscore"):
    start()
else:
    print("BYE!!")